// Products
export const PRODUCT_LIST = "PRODUCT_LIST";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";

// CART
export const CARD_ADD_ITEM = "CARD_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const CART_SAVE_PAYMENT_METHOD = "CART_SAVE_PAYMENT_METHOD";
export const CART_CLEAR = "CART_CLEAR";

// USER
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";

// ORDER
export const ORDER_CREATE = "ORDER_CREATE";
